#!/bin/sh

#for some systems like OSX
#alias md5sum='md5'

realizeCascades -n 100000 -o "output.root?reproducible=fixedname" -d 1 ../levelfiles/Si28_ngam_all_cascades_rfmt_sorted.txt 
#> /dev/null
md5sum output.root
md5sum output.root | awk '{if ($1=="e1f1e59be3e77cb2487e5729a86dc7e3"){system("rm output.root"); print"Checksum passed!"} else {system("rm output.root"); exit 1}}'
