name: nrCascadeSim
dependencies:
  - python>=3.6
  - anaconda
  - numpy
  - scipy
  - matplotlib
#  - ipykernel
#  - nb_conda_kernels
  - anaconda::pytest
  - pip
  - pip:
    - uproot==3.12.0
    - papermill 
    - pandas
