name: test

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        rootver: ['6.20.00', '6.24.06']
        os: [macos-10.15, macos-11, ubuntu-18, ubuntu-16, ubuntu-20]
        exclude: 
          - os: macos-11
            rootver: '6.20.00'
          - os: ubuntu-20
            rootver: '6.20.00'
        include:
          - BUILDLINE: 2
            rootver: '6.20.00'
            os: macos-10.15
            ROOTDIST: "root_v6.20.00.macosx64-10.15-clang110.tar.gz"
          - BUILDLINE: 472
            rootver: '6.24.06'
            os: macos-10.15
            ROOTDIST: "root_v6.24.06.macos-10.15-x86_64-clang120.tar.gz"
          - BUILDLINE: 539
            rootver: '6.24.06'
            os: macos-11
            ROOTDIST: "root_v6.24.06.macos-11.5-x86_64-clang120.tar.gz"
          - BUILDLINE: 203
            rootver: '6.20.00'
            os: ubuntu-16
            ROOTDIST: "root_v6.20.00.Linux-ubuntu16-x86_64-gcc5.4.tar.gz"
          - BUILDLINE: 606
            rootver: '6.24.06'
            os: ubuntu-16
            ROOTDIST: "root_v6.24.06.Linux-ubuntu16-x86_64-gcc5.4.tar.gz"
          - BUILDLINE: 270
            rootver: '6.20.00'
            os: ubuntu-18
            ROOTDIST: "root_v6.20.00.Linux-ubuntu18-x86_64-gcc7.4.tar.gz"
          - BUILDLINE: 573
            rootver: '6.24.06'
            os: ubuntu-18
            ROOTDIST: "root_v6.24.06.Linux-ubuntu18-x86_64-gcc7.5.tar.gz"
          - BUILDLINE: 740
            rootver: '6.24.06'
            os: ubuntu-20
            ROOTDIST: "root_v6.24.06.Linux-ubuntu20-x86_64-gcc9.3.tar.gz"
    steps:
      - uses: actions/checkout@v2
      - name: Initial Setup
        run: | 
          pwd
          ls -a
          sudo chmod 777 .github/install.sh
          source .github/install.sh

          sudo chmod 777 tests/test_realizeCascades.sh
          sudo chmod 777 get_checksums.sh

          mkdir ~/work/nrCascadeSim/nrCascadeSim/nrCascadeSim_build
      - name: Install lcov
        run: |
          wget http://downloads.sourceforge.net/ltp/lcov-1.14.tar.gz
          tar -zxvf lcov-1.14.tar.gz
          cd lcov-1.14
          sudo make install
          cd ../
          lcov --directory ./ --zerocounters
      - name: Install ROOT & make
        run: |
          echo "wget command: wget https://root.cern/download/${{ matrix.ROOTDIST }}"
          wget https://root.cern/download/${{ matrix.ROOTDIST }}
          tar -xzf root_v*
          source root/bin/thisroot.sh
          cd ~/work/nrCascadeSim/nrCascadeSim/nrCascadeSim_build
          root --version

          cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DUSE_GCOV=ON ~/work/nrCascadeSim/nrCascadeSim
          make
          sudo make install
          make tests
          #Send tests to directory they were written to be run from.
          mv readLevelfile realizeAndSave printIsotopeInfo fetchYieldModel ~/work/nrCascadeSim/nrCascadeSim/tests/bin
      - name: Run Tests
        run: |
          cd ~/work/nrCascadeSim/nrCascadeSim
          #activate conda environment
          source activate piptest

          #test help functions
          realizeCascades --help
          regexPlayground --help

          #do the tests
          cd ~/work/nrCascadeSim/nrCascadeSim/tests
          ./test_realizeCascades.sh
          bash test_examples.sh
          regexPlayground
          realizeCascades -n 1 -o "verbosetest.root" ../levelfiles/allge_ngam_WSlow.txt

          cd ../example-usecase
          pytest

      - name: Upload Coverage
        run: |
          cd ~/work/nrCascadeSim/nrCascadeSim
          source ~/work/nrCascadeSim/nrCascadeSim/.github/uploadtocodecov.sh

      - name: make clean
        run: |
          cd ~/work/nrCascadeSim/nrCascadeSim/nrCascadeSim_build
          make clean
          sudo make uninstall
