name: test

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        rootdist: ['6.20.00', '6.24.06']
        os: [macos-10.15, macos-11, ubuntu-18, ubuntu-16, ubuntu-20]
        exclude: 
          - os: macos-11
            rootdist: '6.20.00'
          - os: ubuntu-20
            rootdist: '6.20.00'
        include:
          - BUILDLINE: 2
            rootdist: '6.20.00'
            os: macos-10.15
          - BUILDLINE: 472
            rootdist: '6.24.06'
            os: macos-10.15
          - BUILDLINE: 539
            rootdist: '6.24.06'
            os: macos-11
          - BUILDLINE: 203
            rootdist: '6.20.00'
            os: ubuntu-16
          - BUILDLINE: 606
            rootdist: '6.24.06'
            os: ubuntu-16
          - BUILDLINE: 270
            rootdist: '6.20.00'
            os: ubuntu-18
          - BUILDLINE: 573
            rootdist: '6.24.06'
            os: ubuntu-18
          - BUILDLINE: 740
            rootdist: '6.24.06'
            os: ubutu-20
    steps:
      - uses: actions/checkout@v2
      - name: Initial Setup
        run: | 
          pwd
          ls -a
          sudo chmod 777 .github/install.sh
          source .github/install.sh
      - name: "Get ROOT for MacOS 10 ROOT 6.20"
        if: (matrix.os == 'macos-10.15') && (matrix.rootdist == '6.20.00')
        env: 
          ROOTDIST: "root_v6.20.00.macosx64-10.15-clang110.tar.gz"
        run: |
          echo $ROOTDIST
          echo "wget command: wget https://root.cern/download/$ROOTDIST"
          wget https://root.cern/download/$ROOTDIST
      - name: "Get ROOT for MacOS 10 ROOT 6.24"
        if: (matrix.os == 'macos-10.15') && (matrix.rootdist == '6.24.06')
        env:
          ROOTDIST: "root_v6.20.00.macosx64-10.15-clang110.tar.gz"
        run: |
          echo $ROOTDIST
          echo "wget command: wget https://root.cern/download/$ROOTDIST"
          wget https://root.cern/download/$ROOTDIST
      - name: "Get ROOT for MacOS 11 ROOT 6.24"
        if: (matrix.os == 'macos-11') && (matrix.rootdist == '6.24.06')
        env:
          ROOTDIST: "root_v6.24.06.macos-11-x86_64-clang120.tar.gz"
        run: |
          echo $ROOTDIST
          echo "wget command: wget https://root.cern/download/$ROOTDIST"
          wget https://root.cern/download/$ROOTDIST
      - name: "Get ROOT for Ubuntu 16 ROOT 6.20"
        if: (matrix.os == 'ubuntu-16') && (matrix.rootdist == '6.20.00')
        env:
          ROOTDIST: "root_v6.20.00.Linux-ubuntu16-x86_64-gcc5.4.tar.gz"
        run: |
          echo $ROOTDIST
          echo "wget command: wget https://root.cern/download/$ROOTDIST"
          wget https://root.cern/download/$ROOTDIST
      - name: "Get ROOT for Ubuntu 16 ROOT 6.24"
        if: (matrix.os == 'ubuntu-16') && (matrix.rootdist == '6.24.06')
        env:
          ROOTDIST: "root_v6.24.06.Linux-ubuntu16-x86_64-gcc5.4.tar.gz"
        run: |
          echo $ROOTDIST
          echo "wget command: wget https://root.cern/download/$ROOTDIST"
          wget https://root.cern/download/$ROOTDIST
      - name: "Get ROOT for Ubuntu 18 ROOT 6.20"
        if: (matrix.os == 'ubuntu-18') && (matrix.rootdist == '6.20.00')
        env: 
          ROOTDIST: "root_v6.20.00.Linux-ubuntu18-x86_64-gcc7.4.tar.gz"
        run: |
          echo $ROOTDIST
          echo "wget command: wget https://root.cern/download/$ROOTDIST"
          wget https://root.cern/download/$ROOTDIST
      - name: "Get ROOT for Ubuntu 18 ROOT 6.24"
        if: (matrix.os == 'ubuntu-18') && (matrix.rootdist == '6.24.06')
        env:
          ROOTDIST: "root_v6.24.06.Linux-ubuntu18-x86_64-gcc7.5.tar.gz"
        run: |
          echo $ROOTDIST
          echo "wget command: wget https://root.cern/download/$ROOTDIST"
          wget https://root.cern/download/$ROOTDIST
      - name: "Get ROOT for Ubuntu 20 ROOT 6.24"
        if: (matrix.os == 'ubuntu-20') && (matrix.rootdist == '6.24.06')
        env:
          ROOTDIST: "root_v6.24.06.Linux-ubuntu20-x86_64-gcc9.3.tar.gz"
        run: |
          echo $ROOTIDST
          echo "wget command: wget https://root.cern/download/$ROOTDIST"
          wget https://root.cern/download/$ROOTDIST
      - name: install root
        run: |
          tar -xzf root_v*
          source root/bin/thisroot.sh
          root --version
      - name: set up lcov
        run: |
          wget http://downloads.sourceforge.net/ltp/lcov-1.14.tar.gz
          tar -zxvf lcov-1.14.tar.gz
          cd lcov-1.14
          sudo make install
          cd ../
          lcov --directory ./ --zerocounters
      - name: final setup
        run: |
          root --version

          sudo chmod 777 tests/test_realizeCascades.sh
          sudo chmod 777 get_checksums.sh

          mkdir ~/work/nrCascadeSim/nrCascadeSim/nrCascadeSim_build
          cd ~/work/nrCascadeSim/nrCascadeSim/nrCascadeSim_build
      - name: make
        run: |
          cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DUSE_GCOV=ON ~/work/nrCascadeSim/nrCascadeSim
          make
          sudo make install
          make tests
          #Send tests to directory they were written to be run from.
          mv readLevelfile realizeAndSave printIsotopeInfo fetchYieldModel ~/work/nrCascadeSim/nrCascadeSim/tests/bin
          cd ~/work/nrCascadeSim/nrCascadeSim/
      - name: run tests
        run: |
          #activate conda environment
          source activate piptest

          #test help functions
          realizeCascades --help
          regexPlayground --help

          #do the tests
          cd tests
          ./test_realizeCascades.sh
          bash test_examples.sh
          regexPlayground
          realizeCascades -n 1 -o "verbosetest.root" ../levelfiles/allge_ngam_WSlow.txt

          cd ../example-usecase
          pytest

      - name: upload coverage
        run: |
          cd ~/work/nrCascadeSim/nrCascadeSim
          source ~/work/nrCascadeSim/nrCascadeSim/.github/uploadtocodecov.sh

      - name: make clean
        run: |
          cd ~/build/nrCascadeSim_build
          make clean
          sudo make uninstall
